// Generated by CoffeeScript 1.6.3
(function() {
  var Client, Message, digest, net, proxy, sip, util, _;

  net = require('net');

  sip = require('sip');

  digest = require('sip/digest');

  proxy = require('sip/proxy');

  util = require('util');

  _ = require('underscore');

  Client = function(options) {
    var _this = this;
    this.options = _.defaults(options, Client.defaultOptions);
    this.socket = net.connect({
      port: this.options.port,
      host: this.options.host
    });
    this.sipSocket = sip.start({
      port: 31337
    });
    this.socket.setTimeout(10000);
    this.socket.on('data', function(d) {
      return _this.receive(d);
    });
    this.messages = {};
    this.events = {};
    this.sip = sip;
    return this;
  };

  Client.defaultOptions = {
    debug: false,
    port: 5060
  };

  Client.uuid = function() {
    var f;
    f = function() {
      return Math.floor((1 + Math.random()) * 0x100000).toString(16);
    };
    return [f(), f(), f(), f()].join('-');
  };

  Client.log = function(msg, out) {
    var char;
    if (out == null) {
      out = true;
    }
    char = out === true ? '>' : '<';
    char += ' ';
    msg = msg.split("\n").map(function(line) {
      return char + line;
    }).join("\n");
    return console.log(msg);
  };

  Client.prototype.send = function(string) {
    this.options.debug && Client.log(string);
    return this.socket.write(string);
  };

  Client.prototype.on = function(evt, callback) {
    evt = evt.toLowerCase();
    this.events[evt] = this.events[evt] || [];
    return this.events[evt].push(callback);
  };

  Client.prototype.receive = function(data) {
    var challenge, method, msg, request, response, status;
    msg = sip.parse(data.toString());
    this.options.debug && Client.log(data.toString(), false);
    status = msg.status;
    if (status === 100) {
      return;
    }
    request = this.messages[msg.headers['call-id']];
    switch (status) {
      case void 0:
        method = msg.method.toLowerCase();
        return this.events[method] && this.events[method].forEach(function(cb) {
          return cb(msg);
        });
      case 200:
        return request.events.success.forEach(function(cb) {
          return cb(msg);
        });
      case 407:
        challenge = msg.headers['proxy-authenticate'][0];
        challenge.realm = challenge.realm.replace(/"/g, '');
        request.inc_cseq();
        response = digest.signRequest([challenge], request, msg, {
          user: this.options.user,
          realm: challenge.realm,
          password: this.options.password
        });
        return this.send(sip.stringify(response));
    }
  };

  Client.prototype.message = function(method, uri, headers, body) {
    var m;
    if (body == null) {
      body = '';
    }
    m = new Message(method, uri, headers, body, this.options.host, this.options.user);
    m.client = this;
    return this.messages[m.callid] = m;
  };

  Message = function(method, uri, headers, body, host, user) {
    var defaultHeaders, parts;
    this.seq = 1;
    this.callid = Client.uuid();
    this.events = {
      'success': [],
      'fail': []
    };
    this.method = method.toUpperCase();
    if (typeof uri === 'string') {
      parts = uri.split('@');
      if (parts.length === 1) {
        host = uri;
      } else {

      }
      uri = {
        schema: schema || 'sip',
        user: user,
        host: host
      };
    }
    uri.schema = uri.schema || 'sip';
    uri.host = host || host;
    this.uri = uri;
    defaultHeaders = {
      'call-id': this.callid,
      from: {
        name: 'SipUser',
        uri: {
          schema: uri.schema,
          host: host,
          user: user
        }
      },
      via: [
        {
          version: '2.0',
          protocol: 'tcp',
          host: uri.host
        }
      ],
      cseq: {
        seq: 1,
        method: this.method
      }
    };
    this.headers = _.defaults(headers, defaultHeaders);
    return this;
  };

  Message.prototype.inc_cseq = function() {
    return this.headers.cseq.seq += 1;
  };

  Message.prototype.send = function() {
    this.client.send(this.toString());
    return this;
  };

  Message.prototype.on = function(event, callback) {
    return this.events[event].push(callback);
  };

  Message.prototype.sip = function() {
    return {
      method: this.method,
      uri: this.uri,
      headers: this.headers
    };
  };

  Message.prototype.toString = function() {
    return sip.stringify(this.sip());
  };

  module.exports = Client;

}).call(this);
